name: snap_note
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
     sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2
  rflutter_alert: ^1.1.0
  tinycolor: ^1.0.3
  sqflite: ^1.3.1+1
  path_provider: ^1.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "assets/icon/notes_icon_v1.png"
  image_path_android: "assets/icon/notes_icon_v1.png"
  image_path_ios: "assets/icon/notes_icon_v1.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/notes_icon_v1.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
